name: Run Tests

on: [push]

jobs:
  build:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['5.0']
        python-version: ['3.10']
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Black Check
      uses: jpetrucciani/black-check@master
      with:
        path: './src -t py310'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: supercharge
        mongodb-password: secret
        mongodb-db: supercharge
    - name: Install Poetry
      run: python -m pip install poetry
    - name: Install Deps
      run: python setup.py develop && python -m poetry install
    - name: Run tests
      run: python -m pytest --cov=src --cov-fail-under=85 -vv -c pytest-ci.ini tests/